### ISSUE TITLE
Figure out upload to KNB via dataone package

### ISSUE THREAD

**Issue by fawda123** [tbep-tech/piney-point-metadata#3]
Use this R package https://github.com/DataONEorg/rdataone, first try to https://dev.nceas.ucsb.edu/.  Should be several csv/txt files and a single EML file.

**Comment by fawda123** [comment]
need to authenticate with DataOne first, see `vignette('v02-dataone-federation', package = 'dataone')`

**Comment by fawda123** [comment]
@amoeba I've got a workflow setup for DataOne member node upload starting here: https://github.com/tbep-tech/piney-point-metadata/blob/d992d749877aa4ea43d17af5134779d71e84f052/R/04_upload.R#L1

I'm getting some authentication error issues on lines 26 (DOI generation) and 43 (upload).  Can you please review for any errors?

**Comment by amoeba** [comment]
Hey @fawda123, your code looks fine so I'd guess the authentication issues revolve around what you're setting as your token. Can you run `dataone::echoCredentials(cn)` with that `cn` instance and token set? You should get an R `list` back if you have valid credentials and an error otherwise.

In case it helps, the best way to get an authentication token is to visit https:/dev.nceas.ucsb.edu, sign in, and go to your profile > Settings > Authentication. You might try copying the "Token for DataONE R" value from that page just to get started and then switch back to the environment variable approach I see you're using in your script.

**Comment by fawda123** [comment]
Thanks @amoeba, that worked when I pulled a new token from https:/dev.nceas.ucsb.edu.  I was pulling them from https://www.dataone.org/ previously.  Proof of success: https://dev.nceas.ucsb.edu/view/doi%3A10.5072%2FFK2KW5H83C
